//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaPartyWCF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pizzashopEntities : DbContext
    {
        public pizzashopEntities()
            : base("name=pizzashopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cashier> cashiers { get; set; }
        public DbSet<itemlist> itemlists { get; set; }
        public DbSet<kitchen> kitchens { get; set; }
        public DbSet<orderlist> orderlists { get; set; }
    }
}
